# Generated by Django 5.2.4 on 2026-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('deficiency', models.CharField(max_length=50)),
                ('titles', models.JSONField()),
                ('symptoms', models.JSONField()),
                ('recommendations', models.JSONField()),
            ],
        ),
    ]
