# Generated by Django 5.2.4 on 2026-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fertilizerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True)),
                ('urea_per_acre', models.FloatField(default=100.0)),
                ('dap_per_acre', models.FloatField(default=50.0)),
            ],
        ),
    ]
