# Generated by Django 5.2.4 on 2026-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fertilizerrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizerrate',
            name='dap_per_acre',
        ),
        migrations.RemoveField(
            model_name='fertilizerrate',
            name='urea_per_acre',
        ),
        migrations.AddField(
            model_name='fertilizerrate',
            name='area_type',
            field=models.CharField(choices=[('Barani', 'Barani (Rainfed)'), ('Plain', 'Maedani (Irrigated/Tubewell)')], default='barani', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizerrate',
            name='bags_per_acre',
            field=models.FloatField(default=1.5, help_text='Amount in Bags (e.g. 1.5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizerrate',
            name='deficiency_type',
            field=models.CharField(choices=[('Nitrogen', 'Nitrogen (N)'), ('Phosphorus', 'Phosphorus (P)'), ('Potassium', 'Potassium (K)')], default='nitrogen', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizerrate',
            name='fertilizer_name',
            field=models.CharField(choices=[('Urea', 'Urea'), ('DAP', 'DAP'), ('SOP', 'SOP'), ('NPK', 'NPK')], default='urea', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizerrate',
            name='crop_name',
            field=models.CharField(choices=[('Wheat', 'Wheat (Gandum)'), ('Cotton', 'Cotton (Kapaas)'), ('Rice', 'Rice (Chawal)'), ('Maize', 'Maize (Makkai)'), ('Sugarcane', 'Sugarcane (Kamand)'), ('Mustard', 'Mustard (Sarson)'), ('Bajra', 'Bajra (Pearl Millet)'), ('Potato', 'Potato (Aloo)'), ('Tomato', 'Tomato (Tamatar)'), ('Citrus', 'Citrus (Kinnow/Malta)')], max_length=50),
        ),
    ]
