# Generated by Django 5.2.4 on 2026-03-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_fertilizerrate_dap_per_acre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.EmailField(max_length=254)),
                ('crop', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('area_type', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
