# Generated by Django 5.2.4 on 2026-03-04 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fertilizercalculation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=100)),
                ('deficiency_type', models.CharField(max_length=50)),
                ('price_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('area_acres', models.FloatField()),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('quantity_needed', models.CharField(max_length=100)),
                ('result_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('crop_name', models.CharField(max_length=100)),
                ('deficiency_found', models.CharField(max_length=100)),
                ('suggested_fertilizer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
