# Generated by Django 5.2.4 on 2026-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_result_text_calculationhistory_result_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Urea, DAP, SOP', max_length=50, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.AlterField(
            model_name='fertilizerrate',
            name='area_type',
            field=models.CharField(choices=[('Barani', 'Rainfed'), ('Plain', 'Irrigated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fertilizerrate',
            name='bags_per_acre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fertilizerrate',
            name='crop_name',
            field=models.CharField(choices=[('Wheat', 'Wheat'), ('Cotton', 'Cotton'), ('Rice', 'Rice'), ('Maize', 'Maize'), ('Sugarcane', 'Sugarcane'), ('Potato', 'Potato')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fertilizerrate',
            name='deficiency_type',
            field=models.CharField(choices=[('Nitrogen', 'Nitrogen'), ('Phosphorus', 'Phosphorus'), ('Potassium', 'Potassium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fertilizerrate',
            name='fertilizer_name',
            field=models.CharField(max_length=50),
        ),
    ]
